---
- name: daytime
  type: text
  tags: [astro]

- name: daytime_ext
  type: text
  tags: [astro]

- name: sun_az
  h_name: 'sun azimuth'
  format: '{:.0f}'
  type: number
  tags: [astro]

- name: sun_alt
  h_name: 'sun altitude'
  format: '{:.0f}'
  type: number
  tags: [astro]

- name: moon_phase
  h_name: 'moon phase'
  format: '{:.0f}'
  type: number
  tags: [astro]

- name: sunrise
  type: date
  tags: [astro]

- name: sunset
  type: date
  tags: [astro]

- name: noon
  type: date
  tags: [astro]
