- name: weather_temp
  type: number
  input: mqtt:home/weather/shum/temperature
  ttl: 300
  format: '{:.1f} °C'
  tags: [temperature, out, weather]

- name: weather_pressure
  type: number
  input: mqtt:home/weather/shum/pressure
  ttl: 300
  format: '{:.1f} mbar'
  tags: [out, weather]

- name: weather_wind
  type: number
  input: mqtt:home/weather/shum/windSpeed
  ttl: 300
  format: '{:.1f} м/с'
  tags: [out, weather]

- name: weather_precip
  h_name: 'осадки'
  type: number
  input: mqtt:home/weather/shum/precipIntensity
  ttl: 300
  format: '{:.2f} мм/ч'
  tags: [out, weather]
