---
- name: 'morning'
  trigger:
    time: '0 8 * * *'
    items:
    - item_id: daytime
      to: 'day'
  action:
    - service: log
      data:
        message: 'good morning!'
    - condition_type: state
      item_id: home_mode
      state: 'night'
    - service: set_state
      item_id: home_mode
      value: 'day'